[package]
name = "tree"
version = "0.1.0"
authors = ["grey <fairingrey@gmail.com>"]
edition = "2018"

[dependencies]
exitfailure = "0.5.1"
failure = "0.1.5"
lazy_static = "1.3.0"
regex = "1.1.6"
structopt = "0.2.15"
termcolor = "1.0.4"
